Instrument4Sale/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("InstrumentsApp.urls")),
]

InstrumentsApp/urls.py
from django.urls import path, include
from .views import *
urlpatterns = [
    path('home/', home ,name="home"),
    path('instruments/', instrumentsView, name="instruments"),
    path('brachs/', branchsView, name="branchs"),
    path('about_us/', aboutUs, name="about_us"),
    path('clients/', clientsView, name="clients"),  
    path('instruments_search/', instrumentSearch, name="instruments_search"),
    path('client_search/', clientSearch, name="client_search"),
    path('branch_search/', branchSearch, name="branch_search"),
   path('staff/', include("InstrumentsStaff.urls")),
   
]

InstrumentsStaff/urls.py
from django.urls import path
from .views import *

app_name = 'InstrumentsStaff'

urlpatterns = [
    path('', staffHome , name="staffHome"),
    path('add_instrument', addInstrument, name="add_instrument"),
    path('add_client', addClient, name="add_client"),
    path('add_branch', addBranch, name="add_branch"),

]

InstrumentsApp/models.py
from django.db import models

class Instrument(models.Model):
    type = models.CharField(max_length=20)
    model = models.CharField(max_length=50)
    price = models.IntegerField()
    inStock = models.BooleanField()
    def __str__(self): 
        return f"{self.model}"

class Client(models.Model):
    name = models.CharField(max_length=20)
    lastname = models.CharField(max_length=20)
    email = models.EmailField(max_length=20) 
    def __str__(self):
        return f"{self.name}"

class Branch(models.Model):
    name = models.CharField(max_length=30)
    province = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    
    def __str__(self):
        return f"{self.name}"

InstrumentsStaff/models.py
from django.db import models

# Create your models here.

InstrumentsStaff/forms.py
from django import forms

class InstrumentForm(forms.Form):
    type = forms.CharField(max_length=20, required=True)
    model = forms.CharField(max_length=50, required=True)
    price = forms.IntegerField(required=True)
    inStock = forms.BooleanField(required=False)

class ClientForm(forms.Form):
    name = forms.CharField(max_length=20, required=True)
    lastname = forms.CharField(max_length=20, required=True)
    email = forms.EmailField(max_length=50, required=True) 
    
class BranchForm(forms.Form):
    name = forms.CharField(max_length=30, required=True)
    province = forms.CharField(max_length=30, required=True)
    address = forms.CharField(max_length=50, required=True)

Instrument4Sale/views.py
from django.http import HttpResponse

InstrumentsApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *

def home(request):
    return render(request, "D:/CODERHOUSE Python/Pre-entrega III/Instrument4Sale/InstrumentsApp/templates/apptemplates/home.html")

def instrumentsView(request):
    context = {'models' : Instrument.objects.all()}
    return render(request, "D:/CODERHOUSE Python/Pre-entrega III/Instrument4Sale/InstrumentsApp/templates/apptemplates/instruments_view.html", context)

def branchsView(request):
    context = {'branchs' : Branch.objects.all()}
    return render(request, "D:/CODERHOUSE Python/Pre-entrega III/Instrument4Sale/InstrumentsApp/templates/apptemplates/branchs_view.html", context )

def clientsView(request):
    context = {'clients' : Client.objects.all()}
    return render(request, "D:/CODERHOUSE Python/Pre-entrega III/Instrument4Sale/InstrumentsApp/templates/apptemplates/client_view.html", context )

def aboutUs(request):
    return render(request, "D:/CODERHOUSE Python/Pre-entrega III/Instrument4Sale/InstrumentsApp/templates/apptemplates/about_us.html" )

#===================================================================================================================================================================

#Búsquedas


def instrumentSearch(request):
    if request.GET['search']: 
        patron = request.GET['search']
        modelos = Instrument.objects.filter(model__icontains=patron) 
        contexto = {'models': modelos} 
        return render(request, "apptemplates/instruments_view.html", contexto )
    return render(request, "apptemplates/instruments_view.html")

def clientSearch(request):
    if request.GET['search']: 
        patron = request.GET['search']
        nombres = Client.objects.filter(name__icontains=patron) 
        contexto = {'clients': nombres} 
        return render(request, "apptemplates/client_view.html", contexto )
    return render(request, "apptemplates/client_view.html")

def branchSearch(request):
    if request.GET['search']: 
        patron = request.GET['search']
        nombres = Branch.objects.filter(name__icontains=patron) 
        contexto = {'branchs': nombres} 
        return render(request, "apptemplates/branchs_view.html", contexto )
    return render(request, "apptemplates/branchs_view.html")

InstrumentsStaff/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import *
from InstrumentsApp.models import *
def staffHome(request):
    return render(request, "D:/CODERHOUSE Python/Pre-entrega III/Instrument4Sale/InstrumentsStaff/templates/stafftemplates/home.html")

def addInstrument(request):
    if request.method == "POST":
        formulario = InstrumentForm(request.POST)
        if formulario.is_valid():
            instrument_type = formulario.cleaned_data.get('type')
            instrument_model = formulario.cleaned_data.get('model')
            instrument_price = formulario.cleaned_data.get('price')
            instrument_instock = formulario.cleaned_data.get('inStock')
            instrument = Instrument(type = instrument_type, 
                          model = instrument_model, 
                          price = instrument_price,
                          inStock = instrument_instock) 
            instrument.save()
            return render(request, "stafftemplates/home.html")
    else: 
        formulario = InstrumentForm()
    return render(request, "stafftemplates/instruments_add.html", {"form": formulario})

def addClient(request):
    if request.method == "POST":
        formulario = ClientForm(request.POST)
        if formulario.is_valid():
            client_name = formulario.cleaned_data.get('name')
            client_lastname = formulario.cleaned_data.get('lastname')
            client_email = formulario.cleaned_data.get('email')
            client = Client(name = client_name, 
                          lastname = client_lastname, 
                          email = client_email)
            client.save()
            return render(request, "stafftemplates/home.html")
    else: 
        formulario = ClientForm() 
    return render(request, "stafftemplates/clients_add.html", {"form": formulario})

def addBranch(request):
    if request.method == "POST":
        formulario = BranchForm(request.POST)
        if formulario.is_valid():
            branch_name = formulario.cleaned_data.get('name')
            branch_province = formulario.cleaned_data.get('province')
            branch_address = formulario.cleaned_data.get('address')
            branch = Branch(name = branch_name, 
                          province = branch_province, 
                          address = branch_address)
            branch.save()
            return render(request, "stafftemplates/home.html")
    else: 
        formulario = BranchForm() 
    return render(request, "stafftemplates/branchs_add.html", {"form": formulario})

InstrumentsApp/templates/apptemplates/about_us.html
{% extends 'apptemplates/base.html' %}
{% load static %}


{% block title %}

{% endblock title %}
    

{% block body %}
<section class="py-1 border-bottom">
            <div class="container px-5 my-5 px-5">
                <div class="text-center mb-5">
                    <h2 class="fw-bolder">Sobre nosotros</h2>
                    <p class="lead mb-0">Información que te puede ser útil</p>
                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <!-- Testimonial 1-->
                        <div class="card mb-4">
                            <div class="card-body p-4">
                                <div class="d-flex">
                                    <div class="flex-shrink-0"><i class="bi bi-chat-right-quote-fill text-primary fs-1"></i></div>
                                    <div class="ms-4">
                                        <p class="mb-1">Más de 10 años de experiencia en la venta de instrumentos musicales en el país.</p>
                                        <div class="small text-muted">- Instruments4Sale</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Testimonial 2-->
                        <div class="card mb-4">
                            <div class="card-body p-4">
                                <div class="d-flex">
                                    <div class="flex-shrink-0"><i class="bi bi-chat-right-quote-fill text-primary fs-1"></i></div>
                                    <div class="ms-4">
                                        <p class="mb-1">Inicialmente un emprendimiento familiar, hoy una empresa nacional con múltiples sucursales a lo largo de todo nuestro país.</p>
                                        <div class="small text-muted">- Instruments4Sale</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Testimonial 3-->
                        <div class="card">
                            <div class="card-body p-4">
                                <div class="d-flex">
                                    <div class="flex-shrink-0"><i class="bi bi-chat-right-quote-fill text-primary fs-1"></i></div>
                                    <div class="ms-4">
                                        <p class="mb-1">Consultas:
                                        <p class="mb-1">email - instruments4sale@gmail.com
                                        <p class="mb-1">facebook - instruments4sale</p>
                                        <div class="small text-muted">- Instruments4Sale</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock body %}
    

InstrumentsApp/templates/apptemplates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Instruments4Sale</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'staticApp/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'home' %}">Instruments4Sale</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'instruments' %}">Instrumentos</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'clients' %}">Clientes</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'branchs' %}">Sucursales</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'InstrumentsStaff:staffHome' %}">Staff</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'about_us' %}">Sobre nosotros</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-5">
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <div class="text-center my-5">
                            <h1 class="display-5 fw-bolder text-white mb-2">Encuentra tu instrumento ideal aca</h1>
                            <p class="lead text-white-50 mb-4">Instrumentos de cuerda, viento y percusión!</p>
                            <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
                                <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'instruments' %}">Lista de instrumentos</a>
                                <a class="btn btn-outline-light btn-lg px-4" href="{% url 'InstrumentsStaff:staffHome' %}">Staff</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </header>

        {% block title %}
            
        {% endblock title %}

        
        {% block body %}
            
        {% endblock body %}
    </header>
    <br>
    <br>
    <br/>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container px-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'staticApp/js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

InstrumentsApp/templates/apptemplates/branchs_view.html
{% extends 'apptemplates/base.html' %}
{% load static %}


{% block title %}
<div class="col-12">
    <form style="margin: auto; width: 220px;" class="row row-cols-lg-auto g-3 align-items-center" action="/branch_search" method="get">
                {% csrf_token %} 
        <h4 class="display-7 fw-bolder text-black mb-2">Buscar sucursal: </h4>
            <p>
                <input type="text" name="search" id="search"> 
                <button type="submit" class="btn btn-primary">Enviar</button>
            </p>
</div> 
{% endblock title %}
    

{% block body %}
    <table style="margin: 0px auto;width:35%" class="table table-striped-columns" style=>
        <thead class="table-dark">
        <tr>
            <th>Nombre</th>
            <th>Provincia</th>
            <th>Dirección</th>
        </tr>
        </thead>
        <tbody class="table-group-divider">

    {% for i in branchs %}
        <tr>
            <td>{{ i.name }}</td>
            <td>{{ i.province }}</td>
            <td>{{ i.address }}</td>
        </tr>
    {% endfor %}
    </table>


{% endblock body %}
    

InstrumentsApp/templates/apptemplates/client_view.html
{% extends 'apptemplates/base.html' %}
{% load static %}


{% block title %}
<div class="col-12">
    <form style="margin: auto; width: 220px;" class="row row-cols-lg-auto g-3 align-items-center" action="/client_search" method="get">
                {% csrf_token %} 
        <h4 class="display-7 fw-bolder text-black mb-2">Buscar cliente: </h4>
            <p>
                <input type="text" name="search" id="search"> 
                <button type="submit" class="btn btn-primary">Enviar</button>
            </p>
</div> 
{% endblock title %}



{% block body %}
    <table style="margin: 0px auto;width:40%" class="table table-striped-columns" style=>
        <thead class="table-dark">
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Email</th>

        </tr>
        </thead>
        <tbody class="table-group-divider">

    {% for i in clients %}
        <tr>
            <td>{{ i.id }}</td>
            <td>{{ i.name }}</td>
            <td>{{ i.lastname }}</td>
            <td>{{ i.email }}</td>
        </tr>

    {% endfor %}
    </table>


{% endblock body %}
    

InstrumentsApp/templates/apptemplates/home.html
{% extends 'apptemplates/base.html' %}


{% block title %}
<div class="text-center my-5">
    <h3 class="display-5 fw-bolder text-black mb-2">Inicio</h3>
</div>
{% endblock title %}
    

{% block body %}
<section class="py-5 border-bottom" id="{% url 'home' %}">
    <div class="container px-5 my-5">
        <div class="row gx-5">
            <div class="col-lg-6 mb-5 mb-lg-">
                <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-collection"></i></div>
                <h2 class="h4 fw-bolder">Venta de instrumentos</h2>
                <p>Tenemos a la venta una gran variedad de instrumentos, de marcas desde Gibson hasta Stradivarius. Encontrarás de todo tipo, viento, cuerdas y percusión.</p>
                <a class="text-decoration-none" href="{% url 'instruments' %}">
                    Ver instrumentos
                    <i class="bi bi-arrow-right"></i>
                </a>
            </div>
            <div class="col-lg-6 mb-5 mb-lg-0">
                <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-building"></i></div>
                <h2 class="h4 fw-bolder">Nuestras sucursales</h2>
                <p>Tenemos sucursales distribuidas por todo el país, y cada vez somos mas!</p>
                <a class="text-decoration-none" href="{% url 'branchs' %}">
                    Ver sucursales
                    <i class="bi bi-arrow-right"></i>
                </a>
            </div>
          
</section>
{% endblock body %}
    

InstrumentsApp/templates/apptemplates/instruments_view.html
{% extends 'apptemplates/base.html' %}
{% load static %}


{% block title %}

<div class="col-12">
    <form style="margin: auto; width: 220px;" class="row row-cols-lg-auto g-3 align-items-center" action="/instruments_search" method="get">
                {% csrf_token %} 
        <h4 class="display-7 fw-bolder text-black mb-2">Buscar modelo: </h4>
            <p>
                <input type="text" name="search" id="search"> 
                <button type="submit" class="btn btn-primary">Enviar</button>
            </p>
</div> 
{% endblock title %}



{% block body %}
    
    <table style="margin: 0px auto;width:50%" class="table table-striped-columns" style=>
        <thead class="table-dark">
        <tr>
            <th>Id</th>
            <th>Tipo de instrumento</th>
            <th>Modelo</th>
            <th>Precio (US$)</th>
            <th>En stock</th>

        </tr>
        </thead>
        <tbody class="table-group-divider">

    {% for i in models %}
        <tr>
            <td>{{ i.id }}</td>
            <td>{{ i.type }}</td>
            <td>{{ i.model }}</td>
            <td>{{ i.price }}</td>
            <td>{{ i.inStock }}</td>
        </tr>

    {% endfor %}
    </table>


{% endblock body %}
    

InstrumentsStaff/templates/stafftemplates/branchs_add.html
{% extends 'D:/CODERHOUSE Python/Pre-entrega III/Instrument4Sale/InstrumentsApp/templates/apptemplates/base.html' %}
{% load static %}


{% block title %}
<div class="text-center my-5">
    <h3 class="display-7 fw-bolder text-black mb-2">Agregar una sucursal</h3>
</div>
{% endblock title %}

{% block body %}

<form style="margin: 0px 800px;width:60%" class="row gy-2 gx-3 align-items-center"  action=""method="post">
    <div class="col-auto">
        {% csrf_token %}
        <table>
            {{form.as_table}}    
        </table>
        <button type="submit" class="btn btn-primary">Enviar</button>
    </div>
</form>
{% endblock body %}
    

InstrumentsStaff/templates/stafftemplates/clients_add.html
{% extends 'D:/CODERHOUSE Python/Pre-entrega III/Instrument4Sale/InstrumentsApp/templates/apptemplates/base.html' %}
{% load static %}


{% block title %}
<div class="text-center my-5">
    <h3 class="display-7 fw-bolder text-black mb-2">Agregar un cliente</h3>
</div>
{% endblock title %}

{% block body %}

<form style="margin: 0px 800px;width:60%" class="row gy-2 gx-3 align-items-center"  action=""method="post">
    <div class="col-auto">
        {% csrf_token %}
        <table>
            {{form.as_table}}    
        </table>
        <button type="submit" class="btn btn-primary">Enviar</button>
    </div>
</form>
{% endblock body %}
    

InstrumentsStaff/templates/stafftemplates/home.html
{% extends 'D:/CODERHOUSE Python/Pre-entrega III/Instrument4Sale/InstrumentsApp/templates/apptemplates/base.html' %}
{% load static %}


{% block title %}
<div class="text-center my-5">
    <h3 class="display-7 fw-bolder text-black mb-2">Menú de Staff</h3>
</div>
{% endblock title %}

{% block body %}
<div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
    <a class="btn btn-outline-dark btn-lg px-4" href="{% url 'InstrumentsStaff:add_instrument' %}">Agregar instrumento</a>
    <a class="btn btn-outline-dark btn-lg px-4" href="{% url 'InstrumentsStaff:add_client' %}">Agregar cliente</a>
    <a class="btn btn-outline-dark btn-lg px-4" href="{% url 'InstrumentsStaff:add_branch' %}">Agregar sucursal</a>
</div>
{% endblock body %}
    

InstrumentsStaff/templates/stafftemplates/instruments_add.html
{% extends 'D:/CODERHOUSE Python/Pre-entrega III/Instrument4Sale/InstrumentsApp/templates/apptemplates/base.html' %}
{% load static %}


{% block title %}
<div class="text-center my-5">
    <h3 class="display-7 fw-bolder text-black mb-2">Agregar un instrumento</h3>
</div>
{% endblock title %}

{% block body %}

<form style="margin: 0px 800px;width:60%" class="row gy-2 gx-3 align-items-center"  action=""method="post">
    <div class="col-auto">
        {% csrf_token %}
        <table>
            {{form.as_table}}
            
        </table>
        <button type="submit" class="btn btn-primary">Enviar</button>
    </div>
</form>
{% endblock body %}
    